name: Python CI with Robotframework to execution BurgerEats tests

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  schedule:
    # * é um caractere curinga que corresponde a qualquer coisa
    # '00 16 * * *' executa o trabalho todos os dias às 15:00 UTC-3 (00 19)
    - cron: '00 19 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --shm-size 2g

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==7.0.1
        pip install robotframework-seleniumlibrary==6.3.0
        pip install pyyaml==6.0.1
        pip install chromedriver-autoinstaller

    - name: Install ChromeDriver
      run: |
        python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"

    - name: Run tests
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        robot --outputdir output -v  HANDLESS:S -v BROWSER:chrome -d results tests/

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: robotframework-results
        path: output/